[package]
name = "day07"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "d07p1"
path = "src/part1.rs"

[[bin]]
name = "d07p2"
path = "src/part2.rs"

[dependencies]
itertools = { workspace = true }
