[package]
name = "day12"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "d12p1"
path = "src/part1.rs"

[[bin]]
name = "d12p2"
path = "src/part2.rs"

[dependencies]
rstest = { workspace = true }
nom = { workspace = true }
